---
title: "bob ross"
author: "Jin Kang"
date: "2023-03-08"
output: html_document
---

```{r setup, include=FALSE}
#load libraries
pacman::p_load(pacman,      
               tidyverse,
               showtext
)

#font
font_add_google('Spectral')
showtext_auto()

f1 <- 'Spectral'

#load data
bob_ross <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-02-21/bob_ross.csv')

#create text
title <- str_wrap(
  glue::glue("Colors of Bob Ross")
  )

subtitle <-  
  glue::glue("The frequency of commonly used colors by Boss Rossin the TV show The Joy of Painting across 31 seasons. 
             Larger dots indicate greater frequency.")
  

caption <- str_wrap(
  glue::glue("#TidyTuesday week 8 | Data source: Bob Ross Paintings")
  )
```

```{r data wranggling}
#acknolwedging codes from https://github.com/Honestiore/tidytuesday/blob/main/2023/week8/week8.R

#mutate df to get individual hex in a row for each painiting
colors_speed <- bob_ross %>%
  mutate(color_hex = str_remove_all(color_hex, "\\['"),
         color_hex = str_remove_all(color_hex, "\\']"),
         color_hex = str_remove_all(color_hex, "'")
         ) %>%
  separate_rows(color_hex, sep = ',')

#get unique hex
hexes <- unique(colors_speed$color_hex) %>% str_trim() #remove white space
```

```{r plot}
p1 <- colors_speed %>%
  group_by(season) %>%
  count(color_hex) %>% 
  ggplot(aes(x = season, y = n, size = n*5, color = color_hex)) +
  geom_count(alpha = .4) +
  geom_linerange(aes(x = 1, xmin = 1,xmax = 1,y = 0, ymin = 0, ymax = 26),
                 inherit.aes = F, 
                 alpha = .7, 
                 linetype = 'dashed', 
                 color = '#6d6875') +
  annotate(geom = 'text', 
           x = 1, 
           y = 31, 
           label = 'Season 1', 
           family = f1, 
           size = 6, 
           color = '#6d6875') +
  geom_segment(aes(x = 1, y = 22, xend = 10, yend = 22),
               arrow = arrow(length = unit(0.2, "cm")), 
               color = '#6d6875', 
               size = .75) +
  scale_color_manual(values = hexes) +
  scale_x_continuous(breaks = c(1, 16)) +
  geom_textpath(aes(x = 6.5, y = 28, label = "season increasing"), 
                size = 6, 
                color = '#6d6875') + 
  coord_polar() +
  scale_size(range = c(.1, 10)) +
  theme_void() +
  theme(legend.position = 'none',
        plot.title = element_text(hjust = .5, 
                                   vjust = -1.25, 
                                   family = f1, 
                                   face = "bold", 
                                   size = 25, 
                                   color = '#6d6875'),
        panel.grid.minor = element_blank(),
        plot.caption = element_text(hjust = .5, 
                                     vjust = 25, 
                                     size = 10, 
                                     color = "grey60"),
        plot.subtitle = element_text(hjust = .5,
                                      family = f1,
                                      margin = margin(t = 25, b = 10),
                                      size = 12,
                                      lineheight = 1),
        axis.title = element_blank(),
        axis.text = element_blank()) +
  labs(title = title,
       subtitle = subtitle,
       caption = caption)
  
```

```{r save}
#save as PDF
ggsave(here::here("bob ross", "week_8.pdf"),
       p1, 
       width = 9,
       height = 9,
       device = cairo_pdf)

# convert PDF to PNG
path <- here::here("bob ross")
pdfs <- list.files(path, pattern = "*.pdf", recursive = TRUE)
for(pdf in pdfs) {
  pdftools::pdf_convert(pdf = glue::glue("{path}/{pdf}"), 
              filenames = glue::glue("{path}/{str_remove(pdf, '.pdf')}.png"),
              format = "png", dpi = 500)
}
```

